#jwt:
#  secret: ${JWT_SECRET}
#  expiration: ${JWT_EXPIRATION}
#  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

jwt:
  secret: YOUR_VERY_LONG_RANDOM_SECRET_KEY
  expiration: 3600000
  refresh-expiration: 3600000

geoapify:
  api-key: ${GEOAPIFY_API_KEY}
  base-url: ${GEOAPIFY_BASE_URL}
  url-path: ${GEOAPIFY_URL_PATH}

spring:
  application:
    name: carpool

  datasource:
#    url: jdbc:mysql://localhost:3306/carpool_db?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/carpool_db2?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true